//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_T2104E_NguyenKhacLuong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Không ???c b? tr?ng tr??ng này")]
        [StringLength(32, MinimumLength = 3, ErrorMessage = "Tên có ?? dài t?i thi?u 3 ký t? và t?i ?a 32 ký t?")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Không ???c b? tr?ng tr??ng này")]
        [DataType(DataType.Currency)]
        [RegularExpression(@"^\d+.?\d{0,2}$", ErrorMessage = "nh?p v?i ??nh d?ng ti?n t? vd: 10000,00")]
        public decimal? Price { get; set; }

        [Required(ErrorMessage = "Không ???c b? tr?ng tr??ng này")]
        public int Quanlity { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime ReleaseDate { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
